# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Video Cloud Platform APIs Documentation
email: training@brightcove.com
description:  |- # this means to ignore newlines until "baseurl:"
  With Video Cloud you can deliver fast, innovative, TV-like experiences out-of-the-box, dynamically insert server-side ads to maximize revenue, and reach your audiences wherever they are.

  <p>
    The platform APIs are RESTful APIs that allow you access almost every aspect of the Video Cloud platform programmatically. Typically the APIs are used to create integration between your CMS or other system, or to build custom apps to serve the specific needs of your users.
  </p>
# baseurl: "" # the subpath of your site, e.g. /blog
site_url: "https://ja.apis.support.brightcove.com"
site_domain: "ja.apis.support.brightcove.com"
language: ja

# Build settings
# theme: minima

# local server (for "jekyll serve") will be localhost:{PORT number below}
port: 8460

product: Video Cloud Platform APIs
color: rgb(51, 51, 51)
product_color: rgb(239, 108, 42)
product_icon: "COVE004_Brightcove_Video_Cloud_Logo_RGB_K.svg"
search_id: "017969773216783359937:nencjvjwomg"
feedbackify_id: "16196"
bing_custom_config_id: "83ade92c-9d44-4784-9226-ccf9babcc298"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
# plugins
plugins:
  - jekyll-last-modified-at

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
